//! The bindings generated with the sources in `SQLITE_WASM_RS_SOURCE_DIR`, compiled against those sources.

/// SQLCipher release those sources come from, the shipped one unless a CI leg names its own.
pub const SQLCIPHER_VERSION: &str = match option_env!("SQLCIPHER_LEG_VERSION") {
    Some(version) => version,
    None => sqlcipher_src::SQLCIPHER_VERSION,
};

/// Generated by `sqlite-wasm-rs`'s bindgen setup from SQLCipher's header.
#[expect(
    non_snake_case,
    non_camel_case_types,
    clippy::use_self,
    clippy::unreadable_literal,
    clippy::type_complexity,
    clippy::missing_safety_doc,
    clippy::missing_const_for_fn,
    reason = "bindgen keeps SQLite's C names and shapes"
)]
pub mod sqlcipher {
    include!(concat!(
        env!("SQLITE_WASM_RS_SOURCE_DIR"),
        "/sqlcipher_bindgen.rs"
    ));
}
