"""Builds the vendored directory from an unpacked SQLCipher tree (with sqlite3.c made) and libtomcrypt release, and the Rust list of libtomcrypt files compiled on their own."""

import os
import re
import shutil
import sys

sqlcipher, libtomcrypt, out, sources_rs = sys.argv[1:5]
os.makedirs(out, exist_ok=True)
# A file an upstream release drops must leave the crate.
for name in os.listdir(out):
    path = os.path.join(out, name)
    if os.path.isdir(path):
        shutil.rmtree(path)
    else:
        os.remove(path)

# wasm32 cannot hold a .fini_array section, and SQLCipher offers no switch to skip it until sqlcipher/sqlcipher#622 ships.
FINI_BEFORE = '#else\nstatic void (*const sqlcipher_fini_func)(void) __attribute__((used, section(".fini_array"))) = sqlcipher_fini;\n#endif\n'
FINI_AFTER = '#elif !defined(__wasm__)\nstatic void (*const sqlcipher_fini_func)(void) __attribute__((used, section(".fini_array"))) = sqlcipher_fini;\n#endif\n'


def read(path):
    with open(path, encoding="latin-1") as f:
        return f.read()


def write(path, text):
    with open(path, "w", encoding="latin-1") as f:
        f.write(text)


amalgamation = read(os.path.join(sqlcipher, "sqlite3.c"))
if amalgamation.count(FINI_BEFORE) != 1:
    sys.exit("SQLCipher's .fini_array registration moved, so the wasm guard needs updating")
write(os.path.join(out, "sqlcipher.c"), amalgamation.replace(FINI_BEFORE, FINI_AFTER))
for name in ("sqlite3.h", "sqlite3ext.h"):
    shutil.copy(os.path.join(sqlcipher, name), os.path.join(out, name))
shutil.copy(os.path.join(sqlcipher, "LICENSE.md"), os.path.join(out, "LICENSE-sqlcipher"))

# libtomcrypt's src/ tree as released, built one file per translation unit as upstream does.
tree = os.path.join(out, "libtomcrypt")
shutil.copytree(os.path.join(libtomcrypt, "src"), tree)
shutil.copy(os.path.join(libtomcrypt, "LICENSE"), os.path.join(out, "LICENSE-libtomcrypt"))

sources = []
tables = set()
for root, _, names in os.walk(tree):
    for name in names:
        if name.endswith(".c"):
            path = os.path.join(root, name)
            sources.append(path)
            for table in re.findall(r'#include\s+"([^"]+\.c)"', read(path)):
                tables.add(os.path.normpath(os.path.join(root, table)))
units = sorted(os.path.relpath(p, out).replace(os.sep, "/") for p in sources if p not in tables)

with open(sources_rs, "w", encoding="utf-8") as f:
    f.write("// Generated by tools/assemble.py.\n[\n")
    f.writelines(f'    "{unit}",\n' for unit in units)
    f.write("]\n")
